---
# Copyright 2016-2017 FUJITSU LIMITED

# Configure Memcached.

- name: Copy Memcached configuration.
  template:
    src: memcached-{{ ansible_os_family }}.conf.j2
    dest: "{{ memcached_config_file }}"
    owner: "{{ memcached_user }}"
    group: "{{ memcached_group }}"
    mode: 0644
  register: memcached_config

# On SUSE, memcached listens by default only on 127.0.0.1 but other services
# need to connect to memcached during the ansible-installer run. So
# memcached needs to be restarted directly after reconfiguration.
- name: restart memcached if needed
  service:
    name=memcached
    state=restarted
    enabled=yes
  when: memcached_config|changed
