---
# Copyright 2016-2017 FUJITSU LIMITED

# Configure Memcached.

- name: Copy Memcached configuration.
  template:
    src: memcached-{{ ansible_os_family }}.conf.j2
    dest: "{{ memcached_config_file }}"
    owner: "{{ memcached_user }}"
    group: "{{ memcached_group }}"
    mode: 0644
  register: memcached_config

- name: restart memcached if needed
  service:
    name=memcached
    state=restarted
    enabled=yes
  when: memcached_config|changed
