---
# Copyright 2016-2017 FUJITSU LIMITED

- include: pre_install.yml

- name: Fetch package
  get_url:
    url={{memcached_pkg_src_url}}/memcached-{{ memcached_version }}.x86_64.rpm
    dest={{download_tmp_dir}}/memcached-{{ memcached_version }}.x86_64.rpm
  register: get_url_result
  until: get_url_result.state == 'file'
  retries: 5
  delay: 1
  when: not memcached_use_pkg_mgr

- name: Set owner and group for memcached package
  file:
    path="{{ download_tmp_dir }}/memcached-{{ memcached_version }}.x86_64.rpm"
    state=file
    owner={{ memcached_user }}
    group={{ memcached_group }}
    mode=0640
  when: not memcached_use_pkg_mgr

- name: Install Memcached
  package:
    name="{{ download_tmp_dir }}/memcached-{{ memcached_version }}.x86_64.rpm"
    state=present
  when: not memcached_use_pkg_mgr

- name: Install Memcached.
  package: name=memcached state=present
  when: memcached_use_pkg_mgr
