---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- include: stop.yml
  when: run_mode == 'Stop'

- include: install.yml
  when: run_mode == 'Install' or run_mode == 'Deploy'

- include: configure.yml
  when: run_mode == 'Configure' or run_mode == 'Deploy'

- include: start.yml
  when: run_mode == 'Start' or run_mode == 'Deploy'

- include: status.yml
  when: run_mode == 'Status' or run_mode == 'Deploy'
