---
# Copyright 2016-2017 FUJITSU LIMITED

- name: restart memcached
  service: name=memcached state=restarted enabled=yes

- name: restart firewalld
  service: name=firewalld state=restarted enabled=yes

- name: save iptables
  command: "{{ iptables_save_bin }}"
